name: unidorms
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.0.0
  image_picker: ^1.1.2
  cloud_functions: ^5.0.0
  google_sign_in: ^6.2.1
  firebase_storage: ^12.0.1
  cached_network_image: ^3.1.0
  table_calendar: 3.0.8
  audioplayers: ^6.0.0
  mpesa_flutter_plugin: ^1.6.1
  firebase_messaging: ^15.0.1
  http: ^1.2.1
  encrypt: ^5.0.0



  flutter:
    sdk: flutter
  uuid: ^3.0.4


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
      - assets/images/
      - assets/sounds/


